language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.9 DRF=3.5
  - DJANGO=1.10 DRF=3.5
  - DJANGO=2.0 DRF=3.8
install:
  - pip install -q Django==$DJANGO
  - pip install -q djangorestframework==$DRF
  - pip install pep8
  - pip install -q -e .
before_script:
  - "pep8 drf_generators --exclude=templates && cd tests"
script:
  - python manage.py test
